/*
 * pair_tiles.cuh -- Combination-tiled pair accumulation shared by the
 *                   tomographic 2PCF kernels.
 *
 * The pair kernels are memory-bandwidth bound: the cost of a pair is the
 * geometry load plus the gathers of the map rows of its two pixels.  A
 * "tile" therefore walks every pair of one angular bin ONCE (one thread
 * block per bin, lanes striding the pairs), gathers the full tomographic
 * vectors of both pixels (contiguous in the AoS layout), and accumulates
 * every tomographic combination in registers.  The combinations are
 * generated by compile-time loops so that every local array index is a
 * constant: run-time indexed per-thread arrays spill to thread-local
 * memory and made a first tiled kernel 3x *slower* than the per-row one.
 *
 * Cross-bin estimator.  For a combination (i, j) with i != j every pair
 * contributes in both orientations (tomo bin i at pixel a and j at pixel b,
 * and vice versa).  Both orientations are summed into ONE numerator and
 * ONE weight sum, i.e. the estimator is the ratio of the summed
 * orientations (the standard weighted estimator, TreeCorr's definition)
 * -- not the mean of the two orientation ratios.  This also halves the
 * accumulator count.  Output rows are indexed by the combination k only.
 *
 * Pair geometry loaders.  The tiles are templated on a loader `P` with
 *   P::load(tid, row_a, row_b, ea_R, ea_I, eb_R, eb_I)
 * providing the row indices of both pixels and the components of their
 * pair-frame rotation factors e^{2 i phi}, promoted to the map type T
 * (exact for float -> double; matches the CPU reference kernels).
 *   UnpackedPairs: 24 B per pair (two indices, two complex rotations).
 *   PackedPairs:    8 B per pair = ushort4 {local_a, local_b, angle_a,
 *                  angle_b}: row = row_base[bin] + local (the map rows of
 *                  every (patch, level) block are gathered contiguously by
 *                  the orchestrator, which also keeps the random gathers of
 *                  a thread block inside a sub-MB window); the rotation has
 *                  unit modulus so only its angle is kept, alpha = code *
 *                  2 pi / 65536, evaluated with sincospi(code / 32768)
 *                  (exact argument, 1-ulp result, no range reduction).
 *                  Angle quantisation (<= pi / 65536 = 4.8e-5 rad) changes
 *                  the real part of a pair product by <= 1e-9 relative and
 *                  mixes in <= 1e-4 of its parity-odd imaginary part,
 *                  which averages to zero over the pairs of a bin.
 *
 * Requires common.cuh (BLOCK_SIZE, block reductions) to be included first.
 */

template<typename T, typename C, typename I>
struct UnpackedPairs {
    const I* ind_i;
    const I* ind_j;
    const C* rot_i;
    const C* rot_j;

    __device__ __forceinline__ void load(
        long long tid, long long& row_a, long long& row_b,
        T& ea_R, T& ea_I, T& eb_R, T& eb_I) const
    {
        row_a = (long long)ind_i[tid];
        row_b = (long long)ind_j[tid];
        const C exp_a = rot_i[tid];
        const C exp_b = rot_j[tid];
        ea_R = (T)exp_a.x;
        ea_I = (T)exp_a.y;
        eb_R = (T)exp_b.x;
        eb_I = (T)exp_b.y;
    }

    /* Scalar fields need no rotations (rot_i / rot_j may then be null). */
    __device__ __forceinline__ void load_rows(
        long long tid, long long& row_a, long long& row_b) const
    {
        row_a = (long long)ind_i[tid];
        row_b = (long long)ind_j[tid];
    }
};

__device__ __forceinline__ void sincos_half_turns(float a, float* s, float* c) {
    sincospif(a, s, c);
}
__device__ __forceinline__ void sincos_half_turns(double a, double* s, double* c) {
    sincospi(a, s, c);
}

template<typename T>
struct PackedPairs {
    const ushort4* pairs;   /* (npairs, 4) uint16, 8-byte aligned */
    long long base;         /* first row of this bin's block      */

    __device__ __forceinline__ void load(
        long long tid, long long& row_a, long long& row_b,
        T& ea_R, T& ea_I, T& eb_R, T& eb_I) const
    {
        const ushort4 p = pairs[tid];
        row_a = base + (long long)p.x;
        row_b = base + (long long)p.y;
        /* angle in units of pi: code * 2 pi / 65536 = pi * code / 32768 */
        const T half_turns = (T)(1.0 / 32768.0);
        sincos_half_turns((T)p.z * half_turns, &ea_I, &ea_R);
        sincos_half_turns((T)p.w * half_turns, &eb_I, &eb_R);
    }

    __device__ __forceinline__ void load_rows(
        long long tid, long long& row_a, long long& row_b) const
    {
        const ushort4 p = pairs[tid];
        row_a = base + (long long)p.x;
        row_b = base + (long long)p.y;
    }
};


/*
 * xi+ / xi- for the row-major upper triangle of NS tomographic bins.
 *
 *   xi+ numerator: Re[gamma'_b conj(gamma'_a)] = b_R a_R + b_I a_I
 *   xi- numerator: Re[gamma'_b gamma'_a]       = b_R a_R - b_I a_I
 *
 * shear:   [nrows x NS x 2] interleaved (gamma_1, gamma_2)
 * weights: [nrows x NS]
 * out_num: [xi+ rows k | xi- rows NCOMB + k] x nbins_total; out_den: [k]
 */
template<typename T, int NS, typename ACC, typename P>
__device__ __forceinline__ void tile_xipm(
    const P& pairs, const T* shear, const T* weights,
    const long long start, const long long stop,
    ACC* out_num, ACC* out_den,
    const long long nbins_total, const long long bin_flat)
{
    enum { NCOMB = (NS * (NS + 1)) / 2 };
    const int lane = (int)threadIdx.x;

    ACC acc_p[NCOMB];
    ACC acc_m[NCOMB];
    ACC acc_w[NCOMB];
    for (int k = 0; k < NCOMB; ++k) {
        acc_p[k] = (ACC)0.0;
        acc_m[k] = (ACC)0.0;
        acc_w[k] = (ACC)0.0;
    }

    for (long long tid = start + lane; tid < stop; tid += BLOCK_SIZE) {
        long long row_a, row_b;
        T ea_R, ea_I, eb_R, eb_I;
        pairs.load(tid, row_a, row_b, ea_R, ea_I, eb_R, eb_I);
        row_a *= (long long)NS;
        row_b *= (long long)NS;

        /* Load and rotate every tomographic bin of both pixels once. */
        T a_R[NS], a_I[NS], w_a[NS];
        T b_R[NS], b_I[NS], w_b[NS];
        for (int t = 0; t < NS; ++t) {
            const T ga1 = shear[(row_a + t) * 2];
            const T ga2 = shear[(row_a + t) * 2 + 1];
            const T gb1 = shear[(row_b + t) * 2];
            const T gb2 = shear[(row_b + t) * 2 + 1];
            a_R[t] = ga1 * ea_R - ga2 * ea_I;
            a_I[t] = ga1 * ea_I + ga2 * ea_R;
            b_R[t] = gb1 * eb_R - gb2 * eb_I;
            b_I[t] = gb1 * eb_I + gb2 * eb_R;
            w_a[t] = weights[row_a + t];
            w_b[t] = weights[row_b + t];
        }

        int k = 0;
        for (int i = 0; i < NS; ++i) {
            for (int j = i; j < NS; ++j, ++k) {
                /* A->B: tomo bin i at pixel a, tomo bin j at pixel b */
                const T w_ab = w_a[i] * w_b[j];
                acc_w[k] += (ACC)w_ab;
                acc_p[k] += (ACC)(w_ab * (b_R[j] * a_R[i] + b_I[j] * a_I[i]));
                acc_m[k] += (ACC)(w_ab * (b_R[j] * a_R[i] - b_I[j] * a_I[i]));
                if (i != j) {
                    /* B->A: tomo bin j at pixel a, tomo bin i at pixel b */
                    const T w_ba = w_a[j] * w_b[i];
                    acc_w[k] += (ACC)w_ba;
                    acc_p[k] += (ACC)(w_ba * (b_R[i] * a_R[j] + b_I[i] * a_I[j]));
                    acc_m[k] += (ACC)(w_ba * (b_R[i] * a_R[j] - b_I[i] * a_I[j]));
                }
            }
        }
    }

    /* One block-level reduction per combination (shared-memory footprint
       stays at three BLOCK_SIZE arrays regardless of NCOMB). */
    for (int k = 0; k < NCOMB; ++k) {
        ACC sum_p = acc_p[k];
        ACC sum_m = acc_m[k];
        ACC sum_w = acc_w[k];
        block_reduce_sum_triple<ACC>(sum_p, sum_m, sum_w, &sum_p, &sum_m, &sum_w);
        if (lane == 0) {
            const long long o = ((long long)k) * nbins_total + bin_flat;
            out_num[o] = sum_p;
            out_num[((long long)(NCOMB + k)) * nbins_total + bin_flat] = sum_m;
            out_den[o] = sum_w;
        }
    }
}


/*
 * xi_g (galaxy clustering) for ND density bins: the row-major upper
 * triangle (AUTO_ONLY = 0, NCOMB = ND (ND + 1) / 2) or the auto
 * combinations only (AUTO_ONLY = 1, NCOMB = ND).
 *
 *   numerator: w_a w_b delta_a delta_b, both orientations for i != j
 *
 * density, weights: [nrows x ND]; out_num / out_den: [k x nbins_total]
 */
template<typename T, int ND, int AUTO_ONLY, typename ACC, typename P>
__device__ __forceinline__ void tile_dd(
    const P& pairs, const T* density, const T* weights,
    const long long start, const long long stop,
    ACC* out_num, ACC* out_den,
    const long long nbins_total, const long long bin_flat)
{
    enum { NCOMB = AUTO_ONLY ? ND : (ND * (ND + 1)) / 2 };
    const int lane = (int)threadIdx.x;

    ACC acc_n[NCOMB];
    ACC acc_w[NCOMB];
    for (int k = 0; k < NCOMB; ++k) {
        acc_n[k] = (ACC)0.0;
        acc_w[k] = (ACC)0.0;
    }

    for (long long tid = start + lane; tid < stop; tid += BLOCK_SIZE) {
        long long row_a, row_b;
        pairs.load_rows(tid, row_a, row_b);
        row_a *= (long long)ND;
        row_b *= (long long)ND;

        T d_a[ND], d_b[ND], w_a[ND], w_b[ND];
        for (int t = 0; t < ND; ++t) {
            d_a[t] = density[row_a + t];
            d_b[t] = density[row_b + t];
            w_a[t] = weights[row_a + t];
            w_b[t] = weights[row_b + t];
        }

        int k = 0;
        for (int i = 0; i < ND; ++i) {
            const int j_stop = AUTO_ONLY ? (i + 1) : ND;
            for (int j = i; j < j_stop; ++j, ++k) {
                const T w_ab = w_a[i] * w_b[j];
                acc_w[k] += (ACC)w_ab;
                acc_n[k] += (ACC)(w_ab * d_a[i] * d_b[j]);
                if (i != j) {
                    const T w_ba = w_a[j] * w_b[i];
                    acc_w[k] += (ACC)w_ba;
                    acc_n[k] += (ACC)(w_ba * d_a[j] * d_b[i]);
                }
            }
        }
    }

    for (int k = 0; k < NCOMB; ++k) {
        ACC sum_n = acc_n[k];
        ACC sum_w = acc_w[k];
        block_reduce_sum_pair<ACC>(sum_n, sum_w, &sum_n, &sum_w);
        if (lane == 0) {
            const long long o = ((long long)k) * nbins_total + bin_flat;
            out_num[o] = sum_n;
            out_den[o] = sum_w;
        }
    }
}


/*
 * xi_t (galaxy-galaxy lensing) for the row-major cartesian product of ND
 * lens bins x NS source bins (k = lens * NS + source).
 *
 *   gamma_t = -gamma_1 cos(2 phi) + gamma_2 sin(2 phi)  of the source pixel
 *   numerator: w_lens w_source delta_lens gamma_t, each pair as
 *   (a = lens, b = source) and (b = lens, a = source)
 *
 * density, lens_w: [nrows x ND]; shear: [nrows x NS x 2]; source_w: [nrows x NS]
 * out_num / out_den: [k x nbins_total]
 */
template<typename T, int ND, int NS, typename ACC, typename P>
__device__ __forceinline__ void tile_ds(
    const P& pairs, const T* density, const T* shear,
    const T* lens_w, const T* source_w,
    const long long start, const long long stop,
    ACC* out_num, ACC* out_den,
    const long long nbins_total, const long long bin_flat)
{
    enum { NCOMB = ND * NS };
    const int lane = (int)threadIdx.x;

    ACC acc_n[NCOMB];
    ACC acc_w[NCOMB];
    for (int k = 0; k < NCOMB; ++k) {
        acc_n[k] = (ACC)0.0;
        acc_w[k] = (ACC)0.0;
    }

    for (long long tid = start + lane; tid < stop; tid += BLOCK_SIZE) {
        long long row_a, row_b;
        T ea_R, ea_I, eb_R, eb_I;
        pairs.load(tid, row_a, row_b, ea_R, ea_I, eb_R, eb_I);
        const long long da = row_a * (long long)ND;
        const long long db = row_b * (long long)ND;
        const long long sa = row_a * (long long)NS;
        const long long sb = row_b * (long long)NS;

        T d_a[ND], d_b[ND], dw_a[ND], dw_b[ND];
        for (int l = 0; l < ND; ++l) {
            d_a[l] = density[da + l];
            d_b[l] = density[db + l];
            dw_a[l] = lens_w[da + l];
            dw_b[l] = lens_w[db + l];
        }
        /* Tangential shear of each pixel as the source of the pair */
        T gt_a[NS], gt_b[NS], sw_a[NS], sw_b[NS];
        for (int s = 0; s < NS; ++s) {
            gt_a[s] = -shear[(sa + s) * 2] * ea_R + shear[(sa + s) * 2 + 1] * ea_I;
            gt_b[s] = -shear[(sb + s) * 2] * eb_R + shear[(sb + s) * 2 + 1] * eb_I;
            sw_a[s] = source_w[sa + s];
            sw_b[s] = source_w[sb + s];
        }

        for (int l = 0; l < ND; ++l) {
            for (int s = 0; s < NS; ++s) {
                const int k = l * NS + s;
                /* a = lens, b = source */
                const T w_ab = dw_a[l] * sw_b[s];
                acc_w[k] += (ACC)w_ab;
                acc_n[k] += (ACC)(w_ab * d_a[l] * gt_b[s]);
                /* b = lens, a = source */
                const T w_ba = dw_b[l] * sw_a[s];
                acc_w[k] += (ACC)w_ba;
                acc_n[k] += (ACC)(w_ba * d_b[l] * gt_a[s]);
            }
        }
    }

    for (int k = 0; k < NCOMB; ++k) {
        ACC sum_n = acc_n[k];
        ACC sum_w = acc_w[k];
        block_reduce_sum_pair<ACC>(sum_n, sum_w, &sum_n, &sum_w);
        if (lane == 0) {
            const long long o = ((long long)k) * nbins_total + bin_flat;
            out_num[o] = sum_n;
            out_den[o] = sum_w;
        }
    }
}
